author:
  name: Erwan Normand
baseURL: https://example.com
languageCode: en
menu:
  main:
    - name: About
      url: /about
params:
  description: Example site for the Hugo's Blogpaper theme
  # images:
  # - banner.jpg
title: Blogpaper
theme: Blogpaper
taxonomies:
  series: series